export const GET_POST = 'GET_POST'
export const IS_LOADING = 'IS_LOADING'
export const TOKEN_REQ = 'TOKEN_REQ'
export const IS_LOGGED = 'IS_LOGGED'
export const USER_ID = 'USER_ID'
export const GET_USER = 'GET_USER'